---
version: '3.0'

# By deafult a "latest" tag is applied to the images.
# To refine the tag, build with a suitable .env that defines IMAGE_TAG
# or build with a command line argument: -
#
#   docker-compose build --build-arg IMAGE_TAG=1.0.0

services:

  fragmenstein-base:
    build:
      context: .
      dockerfile: Dockerfile-fragmenstein-base
    image: informaticsmatters/squonk2-fragmenstein-base:${IMAGE_TAG:-latest}

  fragmenstein:
    build:
      context: .
      dockerfile: Dockerfile-fragmenstein
    image: informaticsmatters/squonk2-fragmenstein:${IMAGE_TAG:-latest}

  nextflow:
    build:
      context: .
      dockerfile: Dockerfile-nextflow
    image: informaticsmatters/squonk2-fragmenstein-nextflow:${IMAGE_TAG:-latest}
