---
name: build

# Actions that take place on any non-main branch
# or pull requests to the main branch.

# -----------------
# Control variables (GitHub Secrets)
# -----------------
#
# (n/a)
#
# -----------
# Environment (GitHub Environments)
# -----------
#
# Environment         (n/a)

on:
  push:
    branches-ignore:
    - 'main'
    tags-ignore:
    - '**'
  pull_request:
    branches:
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build-requirements.txt
        pip install -r requirements.txt
    - name: Jote
      run: |
        jote --version
        jote --dry-run
    - name: Build latest
      run: |
        docker-compose build fragmenstein-base
        docker-compose build fragmenstein
        docker-compose build nextflow
